### ISSUE TITLE
Character DNA Pop Quiz Data Population

### ISSUE THREAD

**Issue by sethmerrick** [StoryShop/app#35]
[Character DNA.docx](https://github.com/StoryShop/app/files/186721/Character.DNA.docx)

The above document contains a large set of categorized questions to be used for the random items at the top of the Character DNA section.

Would it be useful for me to convert the above document into a JSON object (or graph), structured to match the plan for implementation?

If so, I'll just need a reference for how to structure the data, plus guidance on where to save the file / by what name.

**Comment by joshdmiller** [comment]
Absolutely - that'd be very helpful!

You can put the file with the other fixtures in `api/fixtures`, perhaps calling the file "genes" (which should also match the collection name). You can also add a data load script to `package.json`.

I think something as simple as this would be cool:

``` json
[
  {
    "gene": "The value of the question here",
    "category": "Personality",
    "_id": "88888888"
  }
]
```

To be consistent, let's use 8-character short ids like we did in the other files. You might want to script that part since there are so many of them.

:+1:
